export const boardStandIds = [
  "majestic",
  "shivajinagar",
  "krmarket",
  "silkboard",
  "hebbal"
];

export const stands = {
  majestic: {
    id: "majestic",
    name: "Majestic",
    routes: [
      "KR Market",
      "Shivajinagar",
      "Malleshwaram",
      "Rajajinagar",
      "Vijayanagar",
      "City Railway Station",
      "Kempegowda Bus Station",
      "Cottonpet",
      "Chickpet",
      "Gandhinagar",
      "Sheshadripuram",
      "Cubbon Park",
      "Basaveshwaranagar",
      "Magadi Road",
      "Mysore Road",
      "Sujatha Talkies",
      "Race Course Road",
      "Anand Rao Circle",
      "Okalipuram",
      "Srirampura",
      "Malleswaram 18th Cross",
      "Mantri Square",
      "Kalasipalya",
      "Town Hall",
      "Freedom Park",
      "Vidhana Soudha",
      "Sampige Road",
      "Nayandahalli",
      "Kengeri",
      "Yeshwanthpur"
    ]
  },
  shivajinagar: {
    id: "shivajinagar",
    name: "Shivajinagar Bus Stand",
    routes: [
      "KR Market",
      "Majestic",
      "Frazer Town",
      "Commercial Street",
      "MG Road",
      "Infantry Road",
      "Cantonment",
      "Russell Market",
      "Ulsoor",
      "Cox Town",
      "Benson Town",
      "Vasanth Nagar",
      "Cunningham Road",
      "Brigade Road",
      "Tasker Town",
      "Queens Road",
      "St Marks Road",
      "Bowring Hospital",
      "Cubbon Park",
      "Lavelle Road",
      "Richmond Circle",
      "Coles Park",
      "Pottery Town",
      "Cooke Town",
      "Pulikeshi Nagar",
      "Lingarajapuram",
      "Indiranagar",
      "Domlur"
    ]
  },
  krmarket: {
    id: "krmarket",
    name: "KR Market",
    routes: [
      "Majestic",
      "Shivajinagar",
      "Chamrajpet",
      "Jayanagar 4th Block",
      "Banashankari",
      "Chickpet",
      "Cottonpet",
      "Kalasipalya",
      "City Market",
      "Basavanagudi",
      "VV Puram",
      "Lalbagh",
      "Wilson Garden",
      "Mysore Road",
      "Town Hall",
      "Avenue Road",
      "SP Road",
      "Mavalli",
      "Minerva Circle",
      "Gandhi Bazaar",
      "Hanumanthanagar",
      "Srinagar",
      "Deepanjali Nagar",
      "Byatarayanapura",
      "Nayandahalli",
      "Uttarahalli",
      "Padmanabhanagar",
      "Kumaraswamy Layout"
    ]
  },
  yeshwanthpur: {
    id: "yeshwanthpur",
    name: "Yeshwanthpur",
    routes: [
      "Majestic",
      "Malleshwaram",
      "Rajajinagar",
      "Peenya",
      "Mathikere",
      "Goraguntepalya",
      "Orion Mall",
      "Sandal Soap Factory",
      "Jalahalli",
      "Nagasandra",
      "Mahalakshmi Layout",
      "Subramanyanagar",
      "MS Ramaiah College",
      "BEL Circle",
      "Dollars Colony",
      "Sanjaynagar",
      "Hebbal",
      "Tumkur Road",
      "Lottegollahalli",
      "Malleswaram 18th Cross",
      "Milk Colony",
      "Nandini Layout",
      "WTC Bengaluru",
      "Peenya 2nd Stage"
    ]
  },
  banashankari: {
    id: "banashankari",
    name: "Banashankari",
    routes: [
      "Jayanagar 4th Block",
      "KR Market",
      "JP Nagar",
      "Padmanabhanagar",
      "Uttarahalli",
      "Katriguppe",
      "Basavanagudi",
      "Girinagar",
      "Kathriguppe",
      "Kumaraswamy Layout",
      "Yediyur",
      "Hanumanthanagar",
      "Srinagar",
      "Hosakerehalli",
      "Rajarajeshwari Nagar",
      "Nayandahalli",
      "Jayanagar 9th Block",
      "Ragigudda",
      "Sarakki",
      "Puttenahalli",
      "Arekere",
      "Ittamadu",
      "Chikkalasandra",
      "Uttarahalli Main Road"
    ]
  },
  jayanagar: {
    id: "jayanagar",
    name: "Jayanagar 4th Block",
    routes: [
      "KR Market",
      "Banashankari",
      "JP Nagar",
      "Basavanagudi",
      "BTM Layout",
      "South End Circle",
      "Lalbagh",
      "Tilak Nagar",
      "Madhavan Park",
      "Wilson Garden",
      "Ragigudda",
      "Jayanagar 9th Block",
      "Jayanagar 3rd Block",
      "Jayanagar 5th Block",
      "Jayanagar East",
      "Dairy Circle",
      "Bannerghatta Road",
      "Mico Layout",
      "Gurappanapalya",
      "Tavarekere",
      "Basavanagudi",
      "Gandhi Bazaar",
      "Nimhans",
      "Lakkasandra"
    ]
  },
  indiranagar: {
    id: "indiranagar",
    name: "Indiranagar",
    routes: [
      "MG Road",
      "Domlur",
      "HAL",
      "Ulsoor",
      "Koramangala",
      "Old Airport Road",
      "Jeevan Bima Nagar",
      "Thippasandra",
      "CV Raman Nagar",
      "Baiyappanahalli",
      "100 Feet Road",
      "Embassy Golf Links",
      "Kodihalli",
      "Murugeshpalya",
      "Kaggadasapura",
      "HAL 2nd Stage",
      "New Thippasandra",
      "Cambridge Layout",
      "Halasuru",
      "Trinity Circle",
      "Brigade Road",
      "Richmond Road",
      "Ejipura",
      "Sony World"
    ]
  },
  koramangala: {
    id: "koramangala",
    name: "Koramangala",
    routes: [
      "Indiranagar",
      "BTM Layout",
      "Madiwala",
      "Ejipura",
      "MG Road",
      "Sony World",
      "Forum Mall",
      "Adugodi",
      "Jakkasandra",
      "HSR Layout",
      "Domlur",
      "St Johns Hospital",
      "Koramangala 1st Block",
      "Koramangala 4th Block",
      "Koramangala 5th Block",
      "Koramangala 6th Block",
      "Koramangala 8th Block",
      "Maharaja Signal",
      "Sarjapur Road",
      "Agara",
      "Bellandur",
      "Dairy Circle",
      "Tavarekere",
      "Lakkasandra"
    ]
  },
  silkboard: {
    id: "silkboard",
    name: "Silk Board",
    routes: [
      "BTM Layout",
      "Koramangala",
      "HSR Layout",
      "Electronic City",
      "Madiwala",
      "Bommanahalli",
      "Hosa Road",
      "Bellandur",
      "Agara",
      "Roopena Agrahara",
      "Kudlu Gate",
      "Mangammanapalya",
      "Central Silk Board",
      "BTM 2nd Stage",
      "Jayadeva Hospital",
      "Bannerghatta Road",
      "Begur",
      "Singasandra",
      "Parappana Agrahara",
      "Bommasandra",
      "Anekal Road",
      "Hosur Road",
      "Haralur",
      "Iblur",
      "Sarjapur Road",
      "Kaikondrahalli"
    ]
  },
  marathahalli: {
    id: "marathahalli",
    name: "Marathahalli",
    routes: [
      "Whitefield",
      "HAL",
      "Bellandur",
      "KR Puram",
      "Doddanekundi",
      "Kundalahalli",
      "Brookefield",
      "Munnekollal",
      "Varthur",
      "Kadubeesanahalli",
      "Yemalur",
      "Outer Ring Road",
      "AECS Layout",
      "Spice Garden",
      "Graphite India",
      "Hope Farm",
      "ITPL",
      "Sarjapur Road",
      "Panathur",
      "Balagere",
      "Devarabisanahalli",
      "HAL Airport Road",
      "Murugeshpalya",
      "Kaggadasapura"
    ]
  },
  whitefield: {
    id: "whitefield",
    name: "Whitefield",
    routes: [
      "Marathahalli",
      "ITPL",
      "KR Puram",
      "Brookefield",
      "Hope Farm",
      "Kadugodi",
      "Varthur",
      "Forum Shantiniketan",
      "EPIP Zone",
      "Pattandur Agrahara",
      "Vydehi Hospital",
      "Channasandra",
      "Nallurhalli",
      "Ramagondanahalli",
      "Siddapura",
      "Kundalahalli",
      "Graphite India",
      "Hoodi",
      "Mahadevapura",
      "Garudachar Palya",
      "Phoenix Marketcity",
      "Immadhihalli",
      "Seegehalli",
      "Belathur"
    ]
  },
  hebbal: {
    id: "hebbal",
    name: "Hebbal",
    routes: [
      "Yelahanka",
      "Manyata Tech Park",
      "RT Nagar",
      "Mekhri Circle",
      "Nagawara",
      "Sahakar Nagar",
      "Jakkur",
      "Esteem Mall",
      "Kodigehalli",
      "Vidyaranyapura",
      "Bangalore Baptist Hospital",
      "Veerannapalya",
      "Kempapura",
      "Lottegollahalli",
      "Sanjaynagar",
      "Dollars Colony",
      "Amruthahalli",
      "Byatarayanapura",
      "Thanisandra",
      "HBR Layout",
      "Kalyan Nagar",
      "Yelahanka New Town",
      "Brindavan College of Engineering",
      "Airport Road"
    ]
  },
  yelahanka: {
    id: "yelahanka",
    name: "Yelahanka",
    routes: [
      "Yelahanka Old Town",
      "Brindavan College of Engineering",
      "Hebbal",
      "Jakkur",
      "Doddaballapur Road",
      "Sahakar Nagar",
      "Vidyaranyapura",
      "Allalasandra",
      "Kogilu",
      "Bagalur",
      "NES Office",
      "Yelahanka New Town",
      "Kendriya Vihar",
      "Attur Layout",
      "Mother Dairy",
      "Judicial Layout",
      "Puttenahalli Lake",
      "Avalahalli",
      "Rajanukunte",
      "MS Palya",
      "Jakkur Aerodrome",
      "Kempegowda International Airport",
      "Devanahalli",
      "Doddaballapur"
    ]
  },
  electroniccity: {
    id: "electroniccity",
    name: "Electronic City",
    routes: [
      "Silk Board",
      "Bommanahalli",
      "Hosur Road",
      "BTM Layout",
      "Hosa Road",
      "Konappana Agrahara",
      "Neeladri Road",
      "Hebbagodi",
      "Wipro Gate",
      "Infosys Gate",
      "Chandapura",
      "Singasandra",
      "Bommasandra",
      "Hulimangala",
      "Jigani",
      "Anekal",
      "Huskur Gate",
      "Veerasandra",
      "PES University EC Campus",
      "Nice Road Junction",
      "Rayasandra",
      "Doddathoguru",
      "Begur",
      "Kudlu Gate"
    ]
  },
  kengeri: {
    id: "kengeri",
    name: "Kengeri",
    routes: [
      "Nayandahalli",
      "Mysore Road",
      "Rajarajeshwari Nagar",
      "Vijayanagar",
      "Uttarahalli",
      "Kengeri Satellite Town",
      "Kumbalgodu",
      "Global Village Tech Park",
      "Pattanagere",
      "Deepanjali Nagar",
      "Nagarbhavi",
      "Bidadi",
      "Jnanabharathi",
      "Bangalore University",
      "RV College of Engineering",
      "Rajarajeshwari Medical College",
      "Ullal",
      "Kommaghatta",
      "Dubasipalya",
      "Mailasandra",
      "Nice Road Junction",
      "Kenchanapura",
      "Kengeri Bus Terminal",
      "Mysore Road Metro"
    ]
  },
  devanahalli: {
    id: "devanahalli",
    name: "Devanahalli",
    routes: [
      "Kempegowda International Airport",
      "Yelahanka",
      "Yelahanka Old Town",
      "Brindavan College of Engineering",
      "Hebbal",
      "Chikkaballapur",
      "Vijayapura",
      "Nandi Hills Cross",
      "Doddaballapur",
      "Bagalur",
      "Sadahalli Gate",
      "Devanahalli Fort",
      "Airport Trumpet",
      "Bettahalasur",
      "Hunasamaranahalli",
      "Rajanukunte",
      "Akkayamma Betta",
      "Avathi",
      "Karahalli",
      "Kannamangala",
      "Budigere Cross",
      "Aerospace Park",
      "KIADB Hardware Park",
      "Chikkajala",
      "Navarathna Agrahara",
      "Sathanur"
    ]
  },
  chickaballapura: {
    id: "chickaballapura",
    name: "Chickaballapura",
    routes: [
      "Devanahalli",
      "Nandi Hills",
      "Kempegowda International Airport",
      "Doddaballapur",
      "Yelahanka",
      "Vijayapura",
      "Bagepalli Road",
      "Sidlaghatta Road",
      "Chickaballapur Bus Stand",
      "Nandi Cross",
      "Muddenahalli",
      "Agalagurki",
      "Peresandra",
      "Kandavara",
      "Mandikal",
      "Gauribidanur Road",
      "Chintamani Road",
      "SJCIT College",
      "Nandi Medical College",
      "Rangoli Halla",
      "Manchenahalli",
      "Kaiwara Cross",
      "Bangalore Road",
      "Devanahalli Fort"
    ]
  }
};

export function getStandUrl(standId) {
  return `/stand/${standId}`;
}
